# Generated by Django 4.1.2 on 2023-01-31 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='added_on',
            field=models.DateField(auto_now=True),
        ),
    ]
