# Generated by Django 4.1.2 on 2023-01-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_marketing_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='status',
            field=models.CharField(choices=[('Fresh', 'Fresh'), ('Open', 'Open'), ('Success', 'Success'), ('Closed', 'Closed')], default='Fresh', max_length=20),
        ),
    ]
