# Generated by Django 4.1.2 on 2023-01-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_marketing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
