# Generated by Django 4.1.4 on 2022-12-09 08:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('place', models.CharField(blank=True, max_length=50, null=True)),
                ('business_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=250)),
                ('contact_person', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_person_number', models.CharField(blank=True, max_length=12, null=True)),
                ('contact_person_designation', models.CharField(blank=True, max_length=50, null=True)),
                ('business_owner_name', models.CharField(max_length=30)),
                ('business_owner_number', models.CharField(max_length=12)),
                ('business_owner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('callbackdate', models.DateField(blank=True, null=True)),
                ('interest_rate', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=25)),
                ('date_added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_date_added_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.leadcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_app.state'),
        ),
        migrations.AddField(
            model_name='leads',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.district'),
        ),
        migrations.AddField(
            model_name='leads',
            name='lead_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.status'),
        ),
        migrations.AddField(
            model_name='leads',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.state'),
        ),
    ]
