# Generated by Django 4.1.4 on 2022-12-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0004_leads_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='contact_person_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
