# Generated by Django 4.1.4 on 2022-12-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0006_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.city'),
        ),
    ]
