# Generated by Django 4.1.4 on 2022-12-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0007_leads_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leads',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
