# Generated by Django 4.1.4 on 2022-12-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0009_extendedusermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='LeadStatus',
        ),
    ]
