# Generated by Django 4.1.4 on 2022-12-13 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0010_rename_status_leadstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='leads',
            name='status',
            field=models.ForeignKey(blank=True, default='freshlead', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.status'),
        ),
    ]
