# Generated by Django 4.1.4 on 2022-12-13 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0011_status_leads_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.status'),
        ),
    ]
