# Generated by Django 4.1.4 on 2022-12-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0013_alter_leads_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='status',
            new_name='statuss',
        ),
    ]
