# Generated by Django 4.1.4 on 2022-12-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0014_rename_status_leads_statuss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='statuss',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.status'),
        ),
    ]
