# Generated by Django 4.1.4 on 2022-12-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0015_alter_leads_statuss'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
