# Generated by Django 4.1.4 on 2022-12-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0016_leads_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='key',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
