# Generated by Django 4.1.4 on 2022-12-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0018_leads_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='is_teamleader',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
