# Generated by Django 4.1.4 on 2022-12-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0021_alter_leads_staff_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadStatus',
            new_name='LeadType',
        ),
        migrations.RenameField(
            model_name='leads',
            old_name='lead_status',
            new_name='lead_type',
        ),
    ]
