# Generated by Django 4.1.4 on 2022-12-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0022_rename_leadstatus_leadtype_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='LeadStatus',
        ),
        migrations.RenameField(
            model_name='leads',
            old_name='statuss',
            new_name='lead_statuss',
        ),
    ]
