# Generated by Django 4.1.4 on 2022-12-15 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0023_rename_status_leadstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='staff_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_app.extendedusermodel'),
        ),
    ]
