# Generated by Django 4.1.4 on 2022-12-15 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crm_app', '0024_alter_leads_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='staff_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
