# Generated by Django 4.1.4 on 2022-12-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0027_alter_leads_staff_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_key', models.CharField(blank=True, max_length=25, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_person_phone_no', models.CharField(blank=True, max_length=12, null=True)),
                ('business_name', models.CharField(max_length=50)),
                ('business_address', models.TextField(max_length=250)),
                ('owner_name', models.CharField(max_length=30)),
                ('business_owner_contact_number', models.CharField(max_length=12)),
            ],
        ),
    ]
