# Generated by Django 4.1.4 on 2022-12-16 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0029_client_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_key', models.CharField(blank=True, max_length=25, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('project_title', models.CharField(blank=True, max_length=30, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('interest_rate', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=25)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('actual_date_added_on', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.leadcategory')),
                ('client_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.client')),
                ('lead_statuss', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.leadstatus')),
            ],
        ),
    ]
