# Generated by Django 4.1.4 on 2022-12-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0030_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client_key',
            new_name='client',
        ),
        migrations.AddField(
            model_name='client',
            name='client_status',
            field=models.CharField(blank=True, choices=[('-1', '-1'), ('0', '0'), ('1', 'ActiveClient'), ('4', '4'), ('5', '5')], default=0, max_length=25),
        ),
    ]
