# Generated by Django 4.1.2 on 2022-12-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0031_rename_client_key_project_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='lead_statuss',
        ),
        migrations.AddField(
            model_name='project',
            name='client_status',
            field=models.CharField(blank=True, choices=[('-1', '-1'), ('0', '0'), ('1', 'ActiveClient'), ('4', '4'), ('5', '5')], default=0, max_length=25),
        ),
    ]
