# Generated by Django 4.1.2 on 2022-12-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0032_remove_project_lead_statuss_project_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_status',
            field=models.CharField(blank=True, choices=[('-1', 'Junk'), ('0', 'Deactivate'), ('1', 'ActiveClient'), ('4', '4'), ('5', '5')], default=0, max_length=25),
        ),
    ]
