# Generated by Django 4.1.2 on 2022-12-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0033_alter_project_client_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client_status',
            field=models.CharField(blank=True, choices=[('Junk', 'Junk'), ('ActiveClient', 'Deactivate'), ('ActiveClient', 'ActiveClient'), ('4', '4'), ('5', '5')], default=0, max_length=25),
        ),
    ]
