# Generated by Django 4.1.2 on 2022-12-20 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0035_clientstatus_remove_client_client_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_statue',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.clientstatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='client_statue',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.clientstatus'),
        ),
    ]
