# Generated by Django 4.1.2 on 2022-12-20 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0036_client_client_statue_project_client_statue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client_statue',
            new_name='client_status',
        ),
    ]
