# Generated by Django 4.1.2 on 2022-12-20 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0038_alter_project_client_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='client_statue',
            new_name='client_status',
        ),
    ]
