# Generated by Django 4.1.2 on 2022-12-22 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0041_alter_project_client_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_status',
        ),
    ]
