# Generated by Django 4.1.2 on 2022-12-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0043_alter_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
