# Generated by Django 4.1.2 on 2022-12-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0046_alter_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='project_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
