# Generated by Django 4.1.2 on 2022-12-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0049_project_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='is_client',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
