# Generated by Django 4.1.2 on 2022-12-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0055_project_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedusermodel',
            name='is_teammember',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
