# Generated by Django 4.1.2 on 2022-12-29 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0056_extendedusermodel_is_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_assignment_key', models.CharField(blank=True, max_length=25, null=True)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('project_assignment', models.CharField(blank=True, max_length=25, null=True)),
                ('message', models.TextField(max_length=250)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_app.extendedusermodel')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.client')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.project')),
            ],
        ),
    ]
