# Generated by Django 4.1.2 on 2022-12-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0057_projectassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='project',
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='Crm_app.project'),
        ),
    ]
