# Generated by Django 4.1.2 on 2022-12-31 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0059_remove_projectassignment_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='title',
            new_name='project_title',
        ),
    ]
