# Generated by Django 4.1.2 on 2022-12-31 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0060_rename_title_leads_project_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='project_title',
            new_name='title',
        ),
    ]
