# Generated by Django 4.1.4 on 2023-01-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0061_rename_project_title_leads_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='message',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
