# Generated by Django 4.1.2 on 2023-01-05 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0062_projectassignment_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leads',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_app.extendedusermodel'),
        ),
    ]
