# Generated by Django 4.1.4 on 2023-01-06 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0064_alter_projectassignment_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectassignment',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Crm_app.project'),
        ),
    ]
