# Generated by Django 4.1.2 on 2023-01-27 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0065_alter_projectassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectassignment',
            options={'verbose_name_plural': 'Project Assignment'},
        ),
    ]
