# Generated by Django 4.1.2 on 2023-02-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0066_alter_projectassignment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='project_assignment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
