# Generated by Django 4.1.2 on 2023-02-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0068_alter_billing_added_on_alter_invoice_added_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
