# Generated by Django 4.1.2 on 2023-02-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0069_alter_projectassignment_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Title'),
        ),
        migrations.RemoveField(
            model_name='projectassignment',
            name='project_assignment',
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project_assignment',
            field=models.ManyToManyField(blank=True, null=True, related_name='task', to='Crm_app.extendedusermodel'),
        ),
    ]
