# Generated by Django 4.1.4 on 2023-02-14 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0071_remove_projectassignment_project_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='Crm_app.project'),
        ),
    ]
