# Generated by Django 4.1.2 on 2023-02-15 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0073_alter_projectassignment_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='Crm_app.project'),
        ),
        migrations.RemoveField(
            model_name='projectassignment',
            name='project_assignment',
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project_assignment',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
