# Generated by Django 4.1.4 on 2023-02-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0077_alter_projectassignment_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='project_assignment',
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project_assignment',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_assignment', to='Crm_app.extendedusermodel'),
        ),
    ]
