# Generated by Django 4.1.4 on 2023-02-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0079_remove_projectassignment_project_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectassignment',
            name='project_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
