# Generated by Django 4.1.4 on 2023-02-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0081_modulemanagement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectassignment',
            name='project_assignment',
        ),
        migrations.AddField(
            model_name='projectassignment',
            name='project_assignment',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_assignment', to='Crm_app.extendedusermodel'),
        ),
    ]
