# Generated by Django 4.1.4 on 2023-02-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0082_remove_projectassignment_project_assignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulemanagement',
            name='module_assigned',
            field=models.ManyToManyField(blank=True, null=True, related_name='module_assigned', to='Crm_app.projectassignment'),
        ),
        migrations.AddField(
            model_name='modulemanagement',
            name='prjct_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prjct_assignment', to='Crm_app.projectassignment'),
        ),
        migrations.AddField(
            model_name='modulemanagement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.project'),
        ),
        migrations.AlterField(
            model_name='projectassignment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='Crm_app.project'),
        ),
    ]
