# Generated by Django 4.1.4 on 2023-02-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0083_modulemanagement_module_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulemanagement',
            name='prjct_assignment',
        ),
    ]
