# Generated by Django 4.1.4 on 2023-02-18 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0084_remove_modulemanagement_prjct_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulemanagement',
            name='prjct_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prjct_assignment', to='Crm_app.projectassignment'),
        ),
    ]
