# Generated by Django 4.1.4 on 2023-02-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0088_modulemanagement_prjct_assignment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleManagement',
        ),
    ]
