# Generated by Django 4.1.4 on 2023-02-21 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0089_delete_modulemanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_module_key', models.CharField(blank=True, max_length=25, null=True)),
                ('module_title', models.CharField(blank=True, max_length=30, null=True)),
                ('module_description', models.TextField(blank=True, max_length=250, null=True)),
                ('module_status', models.CharField(choices=[('0', '0'), ('0', '0'), ('1', '1')], default=1, max_length=2)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_app.extendedusermodel')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Crm_app.project')),
            ],
        ),
    ]
