# Generated by Django 4.1.4 on 2023-02-21 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0091_alter_projectmodule_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectassignment',
            name='project_assignment',
            field=models.ManyToManyField(blank=True, related_name='project_assignment', to='Crm_app.extendedusermodel'),
        ),
        migrations.CreateModel(
            name='ModuleManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_mngmnt_key', models.CharField(blank=True, max_length=25, null=True)),
                ('added_by', models.CharField(blank=True, max_length=25, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('developer_id', models.ManyToManyField(blank=True, related_name='developer_id', to='Crm_app.extendedusermodel')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.projectmodule')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.project')),
                ('project_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.projectassignment')),
            ],
        ),
    ]
