# Generated by Django 4.1.4 on 2023-02-22 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0092_alter_projectassignment_project_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulemanagement',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module', to='Crm_app.projectmodule'),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectmodule', to='Crm_app.project'),
        ),
    ]
