# Generated by Django 4.1.4 on 2023-02-23 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0093_alter_modulemanagement_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulemanagement',
            name='developer',
            field=models.ManyToManyField(blank=True, related_name='developer', to='Crm_app.projectassignment'),
        ),
        migrations.AlterField(
            model_name='modulemanagement',
            name='added_by',
            field=models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Crm_app.extendedusermodel'),
        ),
        migrations.AlterField(
            model_name='modulemanagement',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developers', to='Crm_app.project'),
        ),
    ]
