# Generated by Django 4.1.4 on 2023-03-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0095_remove_modulemanagement_developer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modulemanagement',
            old_name='developer',
            new_name='developerr',
        ),
    ]
