# Generated by Django 4.1.4 on 2023-03-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0096_rename_developer_modulemanagement_developerr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulemanagement',
            name='developerr',
        ),
    ]
