# Generated by Django 4.1.4 on 2023-03-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0097_remove_modulemanagement_developerr'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulemanagement',
            name='developer',
            field=models.ManyToManyField(blank=True, related_name='developer', to='Crm_app.projectassignment'),
        ),
    ]
