# Generated by Django 4.1.2 on 2023-03-10 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0098_modulemanagement_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulemanagement',
            name='developer',
        ),
    ]
