# Generated by Django 4.1.2 on 2023-03-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crm_app', '0099_remove_modulemanagement_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulemanagement',
            name='developer',
            field=models.ManyToManyField(blank=True, related_name='developer', to='Crm_app.extendedusermodel'),
        ),
    ]
